### ISSUE TITLE
Nexus 6P, Ubuntu, 'verity_key.pub' problem

### ISSUE THREAD

**Issue by kittenpirate** [mikeperry-tor/mission-improbable#31] opened 2017-01-06 00:58 UTC
'run_all.sh' results in a successful install of copperheados with the error message: 

"cp: cannot stat 'keys/verity_key.pub': No such file or directory"

I am running a fresh install of ubuntu fully updated with a Nexus 6P. I have a fully updated android sdk and adb. I have ALL of the prerequisites (oracle java 1.7, git, cpio, gcc, g++, openssl)

**Comment by mortenolsendk** [comment] 2017-01-06 15:05
Got the same error.

**tl;dr**: ```sudo apt-get install make```

```/helper-repo/android-simg2img``` wasn't build, and therefore, so i tried to do a ```make``` inside the directory only to find out that i did not have ```make``` installed. After i ```apt-get install make``` and tried ```./run-all ...``` (And python, which caused issues further on) it seamed to work, so I'm guessing this is caused by ```make``` being a build dependency

**Comment by kittenpirate** [comment] 2017-01-09 00:03
Perhaps it would be wise if make was added to the list of prerequisites.

**Comment by kittenpirate** [comment] 2017-01-09 00:56
I already have the newest version of make installed so that is not the cause of my problem.

**Comment by BaraVaq** [comment] 2017-01-09 01:37
The same problem. 
Nexus 5X 
bullhead-factory-2017.01.04.05.44.59.tar.xz
Debian Stable.

**Comment by isislovecruft** [comment] 2017-01-29 07:04
@kittenpirate What does `python --version` tell you?

**Comment by isislovecruft** [comment] 2017-01-30 00:59
This should be fixed with the merge of #35, feel free to reopen the issue persists.

**Closed by isislovecruft** 2017-01-30 00:59 UTC
