### ISSUE TITLE
Mobile data doesn't work on some devices

### ISSUE THREAD

**Issue by micahflee** [mikeperry-tor/mission-improbable#14] opened 2016-11-22 19:16 UTC
If you choose to use a sim card, voice calls and SMS seem to work fine, but no mobile data goes through.

**Comment by neuhaus** [comment] 2016-11-23 15:36
Can you provide more details? Which phone are you using and which version of copperhead?

**Comment by micahflee** [comment] 2016-11-23 18:11
I'm using a Nexus 6P, `angler-nbd91p`. Everything works exactly as it should with wifi. Orbot connects to Tor, and apps that I have allowed through orWall work fine. When I disable wifi, Orbot says there's no internet connection so it can't connect to Tor. When I try using a captive portal browser in orWall that's allowed to bypass Tor, it says there's no internet connection.

I still plan on doing a lot more troubleshooting, but I wanted to start by opening an issue in case others are also experiencing the same thing.

**Comment by patcon** [comment] 2016-11-23 18:35
Ah... I seem to recall having this same issue back when I used to run orwall.

EDIT: ah yes, and it was never resolved, but i've kept my sim in a hotspot for a few years now, so wasn't worth figuring out: https://github.com/EthACKdotOrg/orWall/issues/45

**Comment by mikeperry-tor** [comment] 2016-11-28 21:19
Micah messaged me privately to say that he discovered that this issue was caused by https://github.com/copperhead/bugtracker/issues/340. Apparently you need to update the APN settings?

Closing this as a Dup. IMO the copperhead people should probably change their defaults so it actually works out of the box, but w/e.

**Closed by mikeperry-tor** 2016-11-28 21:19 UTC
